[development]
address = "0.0.0.0"
port = 8000
# workers = [number_of_cpus * 2]
keep_alive = 5
log = "normal"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }
template_dir = "templates/"

[staging]
address = "0.0.0.0"
port = 8000
#workers = [number_of_cpus * 2]
keep_alive = 5
log = "normal"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }
template_dir = "templates/"

[production]
address = "0.0.0.0"
port = 8000
# workers = [number_of_cpus * 2]
keep_alive = 5
log = "critical"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }
template_dir = "templates/"