pub enum Location {
    Unknown,
    United_States,
    United_Kingdom,
    France,
    Bulgaria,
    Slovenia,
    Croatia,
    Bosnia,
    Montenegro,
    Germany,
    Japan,
    Russia,
    Kyrgyzstan,
    Taiwan,
    Estonia,
    Latvia,
    Azerbaijan,
    Lithuania,
    Uzbekistan,
    Sri_Lanka,
    Phillippines,
    Belarus,
    Ukraine,
    Turkmenistan,
    Moldova,
    Armenia,
    Georgia,
    Kazakstan,
    Tajikstan,
    Hong_Kong,
    Greece,
    Lebanon,
    Cyprus,
    Albania,
    Macedonia,
    Malta,
    Ireland,
    Belgium_Luxemburg,
    Portugal,
    Iceland,
    Denmark,
    Poland,
    Romania,
    Hungary,
    South_Africa,
    Ghana,
    Senegal,
    Bahrain,
    Mauritius,
    Morocco,
    Algeria,
    Nigeria,
    Kenya,
    Ivory_Coast,
    Tunisia,
    Tanzania,
    Syria,
    Egypt,
    Brunei,
    Libya,
    Jordan,
    Iran,
    Kuwait,
    Saudi_Arabia,
    United_Arab_Emirates,
    Finland,
    China,
    Norway,
    Israel,
    Sweden,
    Guatemala,
    El_Salvador,
    Honduras,
    Nicargua,
    Costa_Rica,
    Panama,
    Dominican_Republic,
    Mexico,
    Canada,
    Venezuela,
    Switzerland,
    Liechtenstein,
    Columbia,
    Uruguay,
    Peru,
    Bolivia,
    Argentina,
    Chile,
    Paraguay,
    Ecuador,
    Brazil,
    Italy,
    Spain,
    Cuba,
    Slovakia,
    Czech_Republic,
    Serbia,
    Mongolia,
    North_Korea,
    Turkey,
    Netherlands,
    South_Korea,
    Cambodia,
    Thailand,
    Singapore,
    India,
    Vietnam,
    Pakistan,
    Indonesia,
    Austria,
    Australia,
    New_Zealand,
    Malaysia,
    Macau,
}

fn location_from_gs1_code(code: &i8) -> Location {
   match code {
        (0 ..= 19) => Location.Unknown, //United States and Canada
        (20 ..= 29) => Location.Unknown, //Used to issue restricted circulation numbers within a geographic Location
        (30 ..= 39) => Location.United_States //US drugs
        (40 ..= 49) => Location.Unknown, //Used to issue restricted circulation numbers within a geographic Location
        (50 ..= 59) => Location.Unknown, //GS1 US reserved for future use 
        (60 ..= 99) => Location.Unknown, //United States and Canada
        (100 ..= 139) => Location.United_States,
        (200 ..= 299) => Location.Unknown //Used to issue GS1 restricted circulation number within a geographic Location
        (300 ..= 379) => Location.France, //Used for France and Monaco
        380 => Location.Bulgaria,
        383 => Location.Slovenia,
        385 => Location.Croatia,
        387 => Location.Bosnia,
        389 => Location.Montenegro,
        (400 ..= 440) => Location.Germany,
        (450 ..= 459) => Location.Japan,
        (460 ..= 469) => Location.Russia,
        470 => Location.Kyrgyzstan,
        471 => Location.Taiwan,
        474 => Location.Estonia,
        475 => Location.Latvia,
        476 => Location.Azerbaijan,
        477 => Location.Lithuania,
        478 => Location.Uzbekistan,
        479 => Location.Sri_Lanka,
        480 => Location.Phillippines,
        481 => Location.Belarus,
        482 => Location.Ukraine,
        483 => Location.Turkmenistan,
        484 => Location.Moldova,
        485 => Location.Armenia,
        486 => Location.Georgia,
        487 => Location.Kazakstan,
        488 => Location.Tajikstan,
        489 => Location.Hong_Kong,
        (490 ..= 499) => Location.Japan,
        (500 ..= 509) => Location.United_Kingdom,
        (520 ..= 521) => Location.Greece,
        528 => Location.Lebanon,
        529 => Location.Cyprus,
        530 => Location.Albania,
        531 => Location.Macedonia,
        535 => Location.Malta,
        539 => Location.Ireland,
        (540 ..= 549) => Location.Belgium_Luxemburg,
        560 => Location.Portugal,
        569 => Location.Iceland,
        (570 ..= 579) => Location.Denmark,
        590 => Location.Poland,
        594 => Location.Romania,
        599 => Location.Hungary,
        (600 ..= 601) => Location.South_Africa,
        603 => Location.Ghana,
        604 => Location.Senegal,
        608 => Location.Bahrain,
        609 => Location.Mauritius,
        611 => Location.Morocco,
        613 => Location.Algeria,
        615 => Location.Nigeria,
        616 => Location.Kenya,
        618 => Location.Ivory_Coast,
        619 => Location.Tunisia,
        620 => Location.Tanzania,
        621 => Location.Syria,
        622 => Location.Egypt,
        623 => Location.Brunei,
        624 => Location.Libya,
        625 => Location.Jordan,
        626 => Location.Iran,
        627 => Location.Kuwait,
        628 => Location.Saudi_Arabia,
        629 => Location.United_Arab_Emirates,
        (640 ..= 649) => Location.Finland,
        (690 ..= 699) => Location.China,
        (700 ..= 709) => Location.Norway,
        729 => Location.Israel,
        (730 ..= 739) => Location.Sweden,
        740 => Location.Guatemala,
        741 => Location.El_Salvador,
        742 => Location.Honduras,
        743 => Location.Nicargua,
        744 => Location.Costa_Rica,
        745 => Location.Panama,
        746 => Location.Dominican_Republic,
        750 => Location.Mexico,
        (754 ..= 755) => Location.Canada,
        759 => Location.Venezuela,
        (760 ..= 769) => Location.Switzerland,
        (770 ..= 771) => Location.Columbia,
        773 => Location.Uruguay,
        775 => Location.Peru,
        777 => Location.Bolivia,
        (778 ..= 779) => Location.Argentina,
        780 => Location.Chile,
        784 => Location.Paraguay,
        786 => Location.Ecuador,
        (789 ..= 790) => Location.Brazil,
        (800 ..= 839) => Location.Italy,
        (840 ..= 849) => Location.Spain,
        850 => Location.Cuba,
        858 => Location.Slovakia,
        859 => Location.Czech_Republic,
        860 => Location.Serbia,
        865 => Location.Mongolia,
        867 => Location.North_Korea,
        (868 ..= 869) => Location.Turkey,
        (870 ..= 879) => Location.Netherlands,
        880 => Location.South_Korea,
        884 => Location.Cambodia,
        885 => Location.Thailand,
        888 => Location.Singapore,
        890 => Location.India,
        893 => Location.Vietnam,
        896 => Location.Pakistan,
        899 => Location.Indonesia,
        (900 ..= 919) => Location.Austria,
        (930 ..= 939) => Location.Australia,
        (940 ..= 949) => Location.New_Zealand,
        955 => Location.Malaysia,
        958 => Location.Macau
        _ => "Unknown"
    }
}